file:
    - test/functional/api/usersTest.js
    - test/functional/api/treesTest.js
    - test/functional/api/tagsTest.js
    - test/functional/api/recordsTest.js


require: '@babel/register'

timeout: 80000